version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /work_directory/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /work_directory/nginx/html:/usr/share/nginx/html