version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./config:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always
    networks:
      - prometheus_default
networks:
  prometheus_default:
    external: true