---
- name: Utworzenie katalogu
  become: true
  file:
    path: /work_directory/sftp
    state: directory
    owner: "{{ admin_username }}"
    mode: '0755'

- name: Kopiowanie pliku docker-compose
  become: true
  copy:
    src: .
    dest: /work_directory/sftp/
    owner: "{{ admin_username }}"
    mode: "0755"

- name: Uruchomienie serwera sftp
  become: true
  command: 'docker-compose up -d'
  args:
    chdir: '/work_directory/sftp/'
...