---
- name: Utworzenie katalogu
  become: true
  file:
    path: /work_directory/node-exporter
    state: directory
    owner: "{{ admin_username }}"
    mode: '0755'

- name: Kopiowanie Plików
  become: true
  copy:
    src: .
    dest: /work_directory/node-exporter/
    owner: "{{ admin_username }}"
    mode: "0755"

- name: Uruchomienie node-exporter
  become: true
  command: 'docker-compose up -d '
  args:
    chdir: '/work_directory/node-exporter/'
...