version: '3'
services:
  db:
    image: bitnami/postgresql:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami
volumes:
  postgresql_data:
