---
- name: Generowanie klucza SSH
  ansible.builtin.user:
    name: "{{ admin_username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: ssh_key


- name: Tworzenie grupy zasobów
  azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

- name: Tworzenie sieci wirtualnej
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    address_prefixes: "{{ vn_address_prefix }}"

- name: Dodawanie podsieci
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    address_prefix: "{{ subnet_address_prefix }}"
    virtual_network: "{{ vm_name }}"

- name: Utworzenie publicznych adresów IP
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: "{{ public_ip_allocation_method }}"
    name: "{{ vm_name }}"

- name: Utworzenie bezpiecznej grupy sieciowej i otwarcie portów
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    rules:
      - name: "{{ item.name }}"
        protocol: "{{ item.protocol }}"
        destination_port_range: "{{ item.destination_port_range }}"
        access: "{{ item.access }}"
        priority: "{{ item.priority }}"
        direction: "{{ item.direction }}"
  loop: "{{ open_ports }}"
  when: open_ports is defined

- name: Tworzenie wirtualnej karty sieciowej
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    virtual_network: "{{ vm_name }}"
    subnet: "{{ vm_name }}"
    public_ip_name: "{{ vm_name }}"
    security_group: "{{ vm_name }}"


- name: Tworzenie maszyny wirtualnej
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_machine }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key.ssh_public_key }}"
    network_interfaces: "{{ vm_name }}"
    image:
      offer: "{{ os_distro }}"
      publisher: "{{ os_publisher }}"
      sku: "{{ os_sku }}"
      version: "{{ os_version }}"
...
