---
vm_name: serwer2
vm_machine: Standard_D1_v2
admin_username: tgk
public_ip_allocation_method: Static
vn_address_prefix: "10.0.0.0/16"
subnet_address_prefix: "10.0.1.0/24"
os_distro: UbuntuServer
os_publisher: Canonical
os_sku: '18.04-LTS'
os_version: latest
open_ports:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 1002
    direction: Inbound
  - name: http
    protocol: Tcp
    destination_port_range: 80
    access: Allow
    priority: 1001
    direction: Inbound
  - name: grafana
    protocol: Tcp
    destination_port_range: 3000
    access: Allow
    priority: 1005
    direction: Inbound
  - name: prometheus
    protocol: Tcp
    destination_port_range: 9090
    access: Allow
    priority: 1004
    direction: Inbound
  - name: node-exporter
    protocol: "*"
    destination_port_range: 9100
    access: Allow
    priority: 1009
    direction: Inbound
...